### ISSUE TITLE
error while running make command

### ISSUE THREAD

**Issue by alirezadizaji** [cloudflare/jpegtran#8]
Hi,
when i was trying to run make command in linux, I faced the following error:
`py_jpegtran_wrap.c:1575:5: note: (near initialization for ‘PySwigObject_as_number.nb_invert’)
py_jpegtran_wrap.c:1582:6: error: ‘coercion’ undeclared (first use in this function)
 1582 |     (coercion)0,   /*nb_coerce*/
      |      ^~~~~~~~
py_jpegtran_wrap.c:1582:6: note: each undeclared identifier is reported only once for each function it appears in
py_jpegtran_wrap.c:1582:15: error: expected ‘}’ before numeric constant
 1582 |     (coercion)0,   /*nb_coerce*/
      |               ^
py_jpegtran_wrap.c:1564:51: note: to match this ‘{’
 1564 |   static PyNumberMethods PySwigObject_as_number = {
      |                                                   ^
py_jpegtran_wrap.c:1599:9: warning: missing braces around initializer [-Wmissing-braces]
 1599 |       = {
      |         ^
py_jpegtran_wrap.c:1602:2: warning: initialization of ‘long int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
 1602 |  (char *)"PySwigObject",      /* tp_name */
      |  ^
py_jpegtran_wrap.c:1602:2: note: (near initialization for ‘tmp.tp_basicsize’)
py_jpegtran_wrap.c:1605:2: warning: initialization of ‘long int’ from ‘void (*)(PyObject *)’ {aka ‘void (*)(struct _object *)’} makes integer from pointer without a cast [-Wint-conversion]
 1605 |  (destructor)PySwigObject_dealloc,   /* tp_dealloc */
      |  ^
py_jpegtran_wrap.c:1605:2: note: (near initialization for ‘tmp.tp_vectorcall_offset’)
py_jpegtran_wrap.c:1606:2: warning: initialization of ‘PyObject * (*)(PyObject *, char *)’ {aka ‘struct _object * (*)(struct _object *, char *)’} from ‘long int’ makes pointer from integer without a cast [-Wint-conversion]
 1606 |  (printfunc)PySwigObject_print,     /* tp_print */
      |  ^
py_jpegtran_wrap.c:1606:2: note: (near initialization for ‘tmp.tp_getattr’)
py_jpegtran_wrap.c:1610:2: warning: initialization of ‘int (*)(PyObject *, char *, PyObject *)’ {aka ‘int (*)(struct _object *, char *, struct _object *)’} from incompatible pointer type ‘PyObject * (*)(PyObject *, char *)’ {aka ‘struct _object * (*)(struct _object *, char *)’} [-Wincompatible-pointer-types]
 1610 |  (getattrfunc)0,       /* tp_getattr */
      |  ^
py_jpegtran_wrap.c:1610:2: note: (near initialization for ‘tmp.tp_setattr’)
py_jpegtran_wrap.c:1612:2: warning: initialization of ‘PyAsyncMethods *’ {aka ‘struct <anonymous> *’} from incompatible pointer type ‘int (*)(PyObject *, char *, PyObject *)’ {aka ‘int (*)(struct _object *, char *, struct _object *)’} [-Wincompatible-pointer-types]
 1612 |  (setattrfunc)0,       /* tp_setattr */
      |  ^
py_jpegtran_wrap.c:1612:2: note: (near initialization for ‘tmp.tp_as_async’)
py_jpegtran_wrap.c:1613:3: error: ‘cmpfunc’ undeclared (first use in this function)
 1613 |  (cmpfunc)PySwigObject_compare,     /* tp_compare */
      |   ^~~~~~~
py_jpegtran_wrap.c:1613:11: error: expected ‘}’ before ‘PySwigObject_compare’
 1613 |  (cmpfunc)PySwigObject_compare,     /* tp_compare */
      |           ^~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:1599:9: note: to match this ‘{’
 1599 |       = {
      |         ^
py_jpegtran_wrap.c:1599:9: warning: missing braces around initializer [-Wmissing-braces]
py_jpegtran_wrap.c:1660:22: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘ob_type’
 1660 |     pyswigobject_type.ob_type = &PyType_Type;
      |                      ^
py_jpegtran_wrap.c:1564:26: warning: unused variable ‘PySwigObject_as_number’ [-Wunused-variable]
 1564 |   static PyNumberMethods PySwigObject_as_number = {
      |                          ^~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:1562:15: warning: unused variable ‘swigobject_doc’ [-Wunused-variable]
 1562 |   static char swigobject_doc[] = "Swig object carries a C/C++ instance pointer";
      |               ^~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘PySwigPacked_repr’:
py_jpegtran_wrap.c:1709:12: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
 1709 |     return PyString_FromFormat("<Swig Packed at %s%s>", result, v->ty->name);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:1711:12: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
 1711 |     return PyString_FromFormat("<Swig Packed %s>", v->ty->name);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘PySwigPacked_str’:
py_jpegtran_wrap.c:1720:12: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
 1720 |     return PyString_FromFormat("%s%s", result, v->ty->name);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:1722:12: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
 1722 |     return PyString_FromString(v->ty->name);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘_PySwigPacked_type’:
py_jpegtran_wrap.c:1766:9: warning: missing braces around initializer [-Wmissing-braces]
 1766 |       = {
      |         ^
py_jpegtran_wrap.c:1769:2: warning: initialization of ‘long int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
 1769 |  (char *)"PySwigPacked",      /* tp_name */
      |  ^
py_jpegtran_wrap.c:1769:2: note: (near initialization for ‘tmp.tp_basicsize’)
py_jpegtran_wrap.c:1772:2: warning: initialization of ‘long int’ from ‘void (*)(PyObject *)’ {aka ‘void (*)(struct _object *)’} makes integer from pointer without a cast [-Wint-conversion]
 1772 |  (destructor)PySwigPacked_dealloc,   /* tp_dealloc */
      |  ^
py_jpegtran_wrap.c:1772:2: note: (near initialization for ‘tmp.tp_vectorcall_offset’)
py_jpegtran_wrap.c:1773:2: warning: initialization of ‘PyObject * (*)(PyObject *, char *)’ {aka ‘struct _object * (*)(struct _object *, char *)’} from ‘long int’ makes pointer from integer without a cast [-Wint-conversion]
 1773 |  (printfunc)PySwigPacked_print,     /* tp_print */
      |  ^
py_jpegtran_wrap.c:1773:2: note: (near initialization for ‘tmp.tp_getattr’)
py_jpegtran_wrap.c:1774:2: warning: initialization of ‘int (*)(PyObject *, char *, PyObject *)’ {aka ‘int (*)(struct _object *, char *, struct _object *)’} from incompatible pointer type ‘PyObject * (*)(PyObject *, char *)’ {aka ‘struct _object * (*)(struct _object *, char *)’} [-Wincompatible-pointer-types]
 1774 |  (getattrfunc)0,       /* tp_getattr */
      |  ^
py_jpegtran_wrap.c:1774:2: note: (near initialization for ‘tmp.tp_setattr’)
py_jpegtran_wrap.c:1775:2: warning: initialization of ‘PyAsyncMethods *’ {aka ‘struct <anonymous> *’} from incompatible pointer type ‘int (*)(PyObject *, char *, PyObject *)’ {aka ‘int (*)(struct _object *, char *, struct _object *)’} [-Wincompatible-pointer-types]
 1775 |  (setattrfunc)0,       /* tp_setattr */
      |  ^
py_jpegtran_wrap.c:1775:2: note: (near initialization for ‘tmp.tp_as_async’)
py_jpegtran_wrap.c:1776:3: error: ‘cmpfunc’ undeclared (first use in this function)
 1776 |  (cmpfunc)PySwigPacked_compare,     /* tp_compare */
      |   ^~~~~~~
py_jpegtran_wrap.c:1776:11: error: expected ‘}’ before ‘PySwigPacked_compare’
 1776 |  (cmpfunc)PySwigPacked_compare,     /* tp_compare */
      |           ^~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:1766:9: note: to match this ‘{’
 1766 |       = {
      |         ^
py_jpegtran_wrap.c:1766:9: warning: missing braces around initializer [-Wmissing-braces]
py_jpegtran_wrap.c:1823:22: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘ob_type’
 1823 |     pyswigpacked_type.ob_type = &PyType_Type;
      |                      ^
py_jpegtran_wrap.c:1761:15: warning: unused variable ‘swigpacked_doc’ [-Wunused-variable]
 1761 |   static char swigpacked_doc[] = "Swig object carries a C/C++ instance pointer";
      |               ^~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘_SWIG_This’:
py_jpegtran_wrap.c:1868:10: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
 1868 |   return PyString_FromString("this");
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘SWIG_Python_GetSwigThis’:
py_jpegtran_wrap.c:1888:9: warning: implicit declaration of function ‘PyInstance_Check’; did you mean ‘PySequence_Check’? [-Wimplicit-function-declaration]
 1888 |     if (PyInstance_Check(pyobj)) {
      |         ^~~~~~~~~~~~~~~~
      |         PySequence_Check
py_jpegtran_wrap.c:1889:13: warning: implicit declaration of function ‘_PyInstance_Lookup’ [-Wimplicit-function-declaration]
 1889 |       obj = _PyInstance_Lookup(pyobj, SWIG_This());
      |             ^~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:1889:11: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 1889 |       obj = _PyInstance_Lookup(pyobj, SWIG_This());
      |           ^
py_jpegtran_wrap.c: In function ‘SWIG_Python_ConvertFunctionPtr’:
py_jpegtran_wrap.c:2034:17: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 2034 |     char *doc = (((PyCFunctionObject *)obj) -> m_ml -> ml_doc);
      |                 ^
py_jpegtran_wrap.c: In function ‘SWIG_Python_NewShadowInstance’:
py_jpegtran_wrap.c:2103:12: warning: implicit declaration of function ‘PyInstance_NewRaw’ [-Wimplicit-function-declaration]
 2103 |     inst = PyInstance_NewRaw(data->newargs, dict);
      |            ^~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:2103:10: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2103 |     inst = PyInstance_NewRaw(data->newargs, dict);
      |          ^
py_jpegtran_wrap.c: In function ‘SWIG_Python_GetModule’:
py_jpegtran_wrap.c:2221:20: warning: implicit declaration of function ‘PyCObject_Import’; did you mean ‘PyObject_Init’? [-Wimplicit-function-declaration]
 2221 |     type_pointer = PyCObject_Import((char*)"swig_runtime_data" SWIG_RUNTIME_VERSION,
      |                    ^~~~~~~~~~~~~~~~
      |                    PyObject_Init
py_jpegtran_wrap.c:2221:18: warning: assignment to ‘void *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2221 |     type_pointer = PyCObject_Import((char*)"swig_runtime_data" SWIG_RUNTIME_VERSION,
      |                  ^
py_jpegtran_wrap.c: In function ‘SWIG_Python_SetModule’:
py_jpegtran_wrap.c:2284:22: warning: implicit declaration of function ‘Py_InitModule’ [-Wimplicit-function-declaration]
 2284 |   PyObject *module = Py_InitModule((char*)"swig_runtime_data" SWIG_RUNTIME_VERSION,
      |                      ^~~~~~~~~~~~~
py_jpegtran_wrap.c:2284:22: warning: initialization of ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
py_jpegtran_wrap.c:2286:23: warning: implicit declaration of function ‘PyCObject_FromVoidPtr’; did you mean ‘PyLong_FromVoidPtr’? [-Wimplicit-function-declaration]
 2286 |   PyObject *pointer = PyCObject_FromVoidPtr((void *) swig_module, SWIG_Python_DestroyModule);
      |                       ^~~~~~~~~~~~~~~~~~~~~
      |                       PyLong_FromVoidPtr
py_jpegtran_wrap.c:2286:23: warning: initialization of ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
py_jpegtran_wrap.c: In function ‘SWIG_Python_TypeQuery’:
py_jpegtran_wrap.c:2305:19: warning: initialization of ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2305 |   PyObject *key = PyString_FromString(type);
      |                   ^~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:2309:37: warning: implicit declaration of function ‘PyCObject_AsVoidPtr’; did you mean ‘PyLong_AsVoidPtr’? [-Wimplicit-function-declaration]
 2309 |     descriptor = (swig_type_info *) PyCObject_AsVoidPtr(obj);
      |                                     ^~~~~~~~~~~~~~~~~~~
      |                                     PyLong_AsVoidPtr
py_jpegtran_wrap.c:2309:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
 2309 |     descriptor = (swig_type_info *) PyCObject_AsVoidPtr(obj);
      |                  ^
py_jpegtran_wrap.c:2314:11: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2314 |       obj = PyCObject_FromVoidPtr(descriptor, NULL);
      |           ^
py_jpegtran_wrap.c: In function ‘SWIG_Python_TypeError’:
py_jpegtran_wrap.c:2394:21: warning: initialization of ‘const char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2394 |  const char *cstr = str ? PyString_AsString(str) : 0;
      |                     ^~~
py_jpegtran_wrap.c: In function ‘SWIG_AsVal_double’:
py_jpegtran_wrap.c:2496:14: warning: implicit declaration of function ‘PyInt_Check’; did you mean ‘PySet_Check’? [-Wimplicit-function-declaration]
 2496 |   } else if (PyInt_Check(obj)) {
      |              ^~~~~~~~~~~
      |              PySet_Check
py_jpegtran_wrap.c:2497:21: warning: implicit declaration of function ‘PyInt_AsLong’; did you mean ‘PyLong_AsLong’? [-Wimplicit-function-declaration]
 2497 |     if (val) *val = PyInt_AsLong(obj);
      |                     ^~~~~~~~~~~~
      |                     PyLong_AsLong
py_jpegtran_wrap.c: In function ‘SWIG_From_int’:
py_jpegtran_wrap.c:2624:28: warning: implicit declaration of function ‘PyInt_FromLong’; did you mean ‘PyLong_FromLong’? [-Wimplicit-function-declaration]
 2624 |   #define SWIG_From_long   PyInt_FromLong
      |                            ^~~~~~~~~~~~~~
py_jpegtran_wrap.c:2630:10: note: in expansion of macro ‘SWIG_From_long’
 2630 |   return SWIG_From_long  (value);
      |          ^~~~~~~~~~~~~~
py_jpegtran_wrap.c:2624:28: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
 2624 |   #define SWIG_From_long   PyInt_FromLong
      |                            ^
py_jpegtran_wrap.c:2630:10: note: in expansion of macro ‘SWIG_From_long’
 2630 |   return SWIG_From_long  (value);
      |          ^~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘_wrap_transform’:
py_jpegtran_wrap.c:2654:13: warning: implicit declaration of function ‘PyString_Check’; did you mean ‘PyMapping_Check’? [-Wimplicit-function-declaration]
 2654 |         if (PyString_Check(o))
      |             ^~~~~~~~~~~~~~
      |             PyMapping_Check
py_jpegtran_wrap.c:2655:17: warning: assignment to ‘char *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2655 |         arg2[i] = PyString_AsString(PyList_GetItem(obj0,i));
      |                 ^
py_jpegtran_wrap.c: In function ‘swig_varlink_repr’:
py_jpegtran_wrap.c:2958:12: warning: returning ‘int’ from a function with return type ‘PyObject *’ {aka ‘struct _object *’} makes pointer from integer without a cast [-Wint-conversion]
 2958 |     return PyString_FromString("<Swig global variables>");
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘swig_varlink_str’:
py_jpegtran_wrap.c:2963:21: warning: initialization of ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 2963 |     PyObject *str = PyString_FromString("(");
      |                     ^~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c: In function ‘swig_varlink_print’:
py_jpegtran_wrap.c:2977:18: warning: format ‘%s’ expects argument of type ‘char *’, but argument 3 has type ‘int’ [-Wformat=]
 2977 |     fprintf(fp,"%s\n", PyString_AsString(str));
      |                 ~^     ~~~~~~~~~~~~~~~~~~~~~~
      |                  |     |
      |                  |     int
      |                  char *
      |                 %d
py_jpegtran_wrap.c: In function ‘swig_varlink_type’:
py_jpegtran_wrap.c:3034:9: warning: missing braces around initializer [-Wmissing-braces]
 3034 |       = {
      |         ^
py_jpegtran_wrap.c:3037:9: warning: initialization of ‘long int’ from ‘char *’ makes integer from pointer without a cast [-Wint-conversion]
 3037 |         (char *)"swigvarlink",              /* Type name (tp_name) */
      |         ^
py_jpegtran_wrap.c:3037:9: note: (near initialization for ‘tmp.tp_basicsize’)
py_jpegtran_wrap.c:3040:9: warning: initialization of ‘long int’ from ‘void (*)(PyObject *)’ {aka ‘void (*)(struct _object *)’} makes integer from pointer without a cast [-Wint-conversion]
 3040 |         (destructor) swig_varlink_dealloc,   /* Deallocator (tp_dealloc) */
      |         ^
py_jpegtran_wrap.c:3040:9: note: (near initialization for ‘tmp.tp_vectorcall_offset’)
py_jpegtran_wrap.c:3041:9: warning: initialization of ‘PyObject * (*)(PyObject *, char *)’ {aka ‘struct _object * (*)(struct _object *, char *)’} from ‘long int’ makes pointer from integer without a cast [-Wint-conversion]
 3041 |         (printfunc) swig_varlink_print,     /* Print (tp_print) */
      |         ^
py_jpegtran_wrap.c:3041:9: note: (near initialization for ‘tmp.tp_getattr’)
py_jpegtran_wrap.c:3042:9: warning: initialization of ‘int (*)(PyObject *, char *, PyObject *)’ {aka ‘int (*)(struct _object *, char *, struct _object *)’} from incompatible pointer type ‘PyObject * (*)(PyObject *, char *)’ {aka ‘struct _object * (*)(struct _object *, char *)’} [-Wincompatible-pointer-types]
 3042 |         (getattrfunc) swig_varlink_getattr, /* get attr (tp_getattr) */
      |         ^
py_jpegtran_wrap.c:3042:9: note: (near initialization for ‘tmp.tp_setattr’)
py_jpegtran_wrap.c:3043:9: warning: initialization of ‘PyAsyncMethods *’ {aka ‘struct <anonymous> *’} from incompatible pointer type ‘int (*)(PyObject *, char *, PyObject *)’ {aka ‘int (*)(struct _object *, char *, struct _object *)’} [-Wincompatible-pointer-types]
 3043 |         (setattrfunc) swig_varlink_setattr, /* Set attr (tp_setattr) */
      |         ^
py_jpegtran_wrap.c:3043:9: note: (near initialization for ‘tmp.tp_as_async’)
py_jpegtran_wrap.c:3045:9: warning: initialization of ‘PyNumberMethods *’ {aka ‘struct <anonymous> *’} from incompatible pointer type ‘PyObject * (*)(PyObject *)’ {aka ‘struct _object * (*)(struct _object *)’} [-Wincompatible-pointer-types]
 3045 |         (reprfunc) swig_varlink_repr,       /* tp_repr */
      |         ^
py_jpegtran_wrap.c:3045:9: note: (near initialization for ‘tmp.tp_as_number’)
py_jpegtran_wrap.c:3051:9: warning: initialization of ‘PyObject * (*)(PyObject *, PyObject *)’ {aka ‘struct _object * (*)(struct _object *, struct _object *)’} from incompatible pointer type ‘PyObject * (*)(PyObject *)’ {aka ‘struct _object * (*)(struct _object *)’} [-Wincompatible-pointer-types]
 3051 |         (reprfunc)swig_varlink_str,        /* tp_str */
      |         ^
py_jpegtran_wrap.c:3051:9: note: (near initialization for ‘tmp.tp_getattro’)
py_jpegtran_wrap.c:3056:9: warning: initialization of ‘int (*)(PyObject *, int (*)(PyObject *, void *), void *)’ {aka ‘int (*)(struct _object *, int (*)(struct _object *, void *), void *)’} from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
 3056 |         varlink__doc__,                     /* tp_doc */
      |         ^~~~~~~~~~~~~~
py_jpegtran_wrap.c:3056:9: note: (near initialization for ‘tmp.tp_traverse’)
py_jpegtran_wrap.c:3034:9: warning: missing braces around initializer [-Wmissing-braces]
 3034 |       = {
      |         ^
py_jpegtran_wrap.c:3072:19: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘ob_type’
 3072 |       varlink_type.ob_type = &PyType_Type;
      |                   ^
py_jpegtran_wrap.c: In function ‘SWIG_Python_FixMethods’:
py_jpegtran_wrap.c:3151:17: warning: initialization discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
 3151 |       char *c = methods[i].ml_doc;
      |                 ^~~~~~~
py_jpegtran_wrap.c: In function ‘init_jpegtran_wrap’:
py_jpegtran_wrap.c:3203:5: warning: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
 3203 |   m = Py_InitModule((char *) SWIG_name, SwigMethods);
      |     ^
At top level:
py_jpegtran_wrap.c:1761:15: warning: ‘swigpacked_doc’ defined but not used [-Wunused-variable]
 1761 |   static char swigpacked_doc[] = "Swig object carries a C/C++ instance pointer";
      |               ^~~~~~~~~~~~~~
py_jpegtran_wrap.c:1562:15: warning: ‘swigobject_doc’ defined but not used [-Wunused-variable]
 1562 |   static char swigobject_doc[] = "Swig object carries a C/C++ instance pointer";
      |               ^~~~~~~~~~~~~~
py_jpegtran_wrap.c:1564:26: warning: ‘PySwigObject_as_number’ defined but not used [-Wunused-variable]
 1564 |   static PyNumberMethods PySwigObject_as_number = {
      |                          ^~~~~~~~~~~~~~~~~~~~~~
py_jpegtran_wrap.c:1530:1: warning: ‘swigobject_methods’ defined but not used [-Wunused-variable]
 1530 | swigobject_methods[] = {
      | ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:37: all] Error 1`
do you know how to fix this?

**Comment by kornelski** [comment]
This error does not come from `jpegtran`, so we can't help you. The error is from some Python project that is trying to use jpegtran, so you need to ask author of `py_jpegtran_wrap`.

**Comment by alirezadizaji** [comment]
Ok, Thanks
